///Firebase

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN'; //Giriş
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP'; //createuser
export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT'; //çıkış

export const REQUEST_ADD_PRODUCT_FB = 'REQUEST_ADD_PRODUCT_FB'; //db add
export const REQUEST_GET_PRODUCTS_FB = 'REQUEST_GET_PRODUCTS_FB'; //db get
export const FIREBASE_PRODUCTS_LISTENER = 'FIREBASE_PRODUCTS_LISTENER'; //all db
export const REQUEST_GET_ALL_PRODUCTS = 'REQUEST_GET_ALL_PRODUCTS';

export const FAVORITES_PRODUCTS = 'FAVORITES_PRODUCTS'; //FAVORİ PRODUCTS
export const GET_FAVORITES_PRODUCTS = 'GET_FAVORITES_PRODUCTS';
export const SELECT_PTODUCT = 'SELECT_PTODUCT';
