///Firebase

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const CREATE_FB = 'CREATE_FB';
export const LOGIN_FB = 'LOGIN_FB';
export const LOGOUT_FB = 'LOGOUT_FB';

//Product
export const SET_FAVORI_FB = 'SET_FAVORI_FB';
export const GET_FAVORI_FB = 'GET_FAVORI_FB';
export const FIREBASE_FAVORITES_LISTENER = 'FIREBASE_FAVORITES_LISTENER';
export const FIREBASE_PRODUCTS_LISTENER = 'FIREBASE_PRODUCTS_LISTENER';
export const ADD_PRODUCTS_FB = 'ADD_PRODUCTS_FB';
export const GET_PRODUCTS_FB = 'GET_PRODUCTS_FB';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';

export const REQUEST_ADD_PRODUCT_FB = 'REQUEST_ADD_PRODUCT_FB'; //db add
export const REQUEST_GET_PRODUCTS_FB = 'REQUEST_GET_PRODUCTS_FB'; //db get
export const REQUEST_GET_ALL_PRODUCTS = 'REQUEST_GET_ALL_PRODUCTS';

export const FAVORITES_PRODUCTS = 'FAVORITES_PRODUCTS'; //FAVORİ PRODUCTS
export const GET_FAVORITES_PRODUCTS = 'GET_FAVORITES_PRODUCTS';
export const FIREBASE_FAV_LIST = 'FIREBASE_FAV_LIST';
export const SELECT_PTODUCT = 'SELECT_PTODUCT';
